export const washKeys = {
  id: 'id',
  requestUid: 'requestUid',
  requestDate: 'requestDate',
  sendDate: 'sendDate',
  company: 'company',
  deliveryStatus: 'deliveryStatus',
  washStatus: 'washStatus',
  estimatedDate: 'estimatedDate',
  registeredDelivery: 'registeredDelivery',
  productName: 'productName',
  productUid: 'productUid',
  requestQuantity: 'requestQuantity',
  stockQuantity: 'stockQuantity',
  returnQuantity: 'returnQuantity',
  returnConfirmQuantity: 'returnConfirmQuantity',
  returnReason: 'returnReason',
  recieveQuantity: 'recieveQuantity',
  salesUnit: 'salesUnit',
  category1: 'category1',
  category2: 'category2',
  category3: 'category3',
  returnStatus: 'returnStatus',
  deductedQuantity: 'deductedQuantity',
  deductedAmount: 'deductedAmount',
  waitQuantity: 'waitQuantity',
  onWashingQuantity: 'onWashingQuantity',
  finishQuantity: 'finishQuantity',
  orderNumber: 'orderNumber',
};

export const announcementKeys = {
  id: 'id',
  title: 'title',
  content: 'content',
  attachedFile: 'attachedFile',
  createdAt: 'createdAt',
};

export const calcKeys = {
  id: 'id',
  price: 'price',
  total: 'total',
  order: 'order',
  calc: 'calc',
  spendDeposit: 'spendDeposit',
  createdAt: 'createdAt',
  company: 'company',
};
